### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp1-graph-fondacci-frazer#1]
- [x] Il y a encore beaucoup de code en commun entre DFS et BFS

- [x] Node ne surcharge pas la méthode `hashcode`, quel est la conséquence ?

**Comment by hartyshow** [comment]
- Nous avons essayé de factoriser un petit peu de code entre les deux classes de parcours, nous espérons que c'est mieux maintenant.

- Le risque de ne pas override la méthode hashCode() est que Java utilise la méthode par défaut, définie dans Object, qui peut donner des hash code différents même pour deux objets qui sont pourtant égaux selon la méthode equals(). Depuis, certaines collections comme HashSet, HashMap ou HashTable utilisent les hash code pour stocker et retrouver les données. Or si les méthodes equals() ET hashCode() ne sont pas redéfinies cela peut mal fonctionner et causer des problèmes de références.

**Comment by Slashgear** [comment]
- [ ] Il est encore possible de grouper les deux algo.
- [ ] On pourrait ranger en packages les classes (attention les packages c'est en minuscule en java)

**Comment by Slashgear** [comment]
Ok ça me va, si c'est bien vous qui avez trouvé. J'ai *exactement* trouvé la même dans des autres rendus de TP.

Expliquer moi donc comment cela marche ?

**Comment by hartyshow** [comment]
Quelque soit la méthode de visite du graphe, la majorité du code est identique. Ainsi, nous avons centralisé l'ancien code de BFSMethod et DFSMethod au sein de la classe ParcoursMethod. Cette classe contient une référence au graphe actuellement traité ainsi que deux listes : les nœuds visités (visitedNodes) et les nœuds pas encore visités (unvisitedNodes). 
Toute la différence se joue dans la méthode next() qui va faire appel aux méthodes filles nécessaires de DFSMethod et BFSMethod. En voici l'explication : 

Tant que la liste unvisitedNodes n'est pas vide, on va récupérer le nœud à traiter. Pour ce faire, il est nécessaire de faire appel à la méthode getNextUnvisitedNode(), qui est en abstract dans la classe ParcoursMethod et ainsi définie dans les classes filles (DFS/BFSMethod). Cette méthode est très courte, pour le parcours en profondeur, on va récupérer le dernier nœud de la liste des nœuds non-visités tandis que pour le parcours en largeur, on va récupérer le premier nœud de cette même liste. La question est : comment le programme peut-il savoir quelle classe il doit choisir entre DFS et BFS ? Cela se passe au niveau de la classe de test TestSearch qui choisit explicitement le type d'Iterator souhaité, par exemple : 
Iterator<Node> bfsIteratorDirected = dg.creerBFSIterator(na);
Ensuite tout le reste du code est commun aux deux types de parcours : on ajoute le nœud actuel à la liste des nœuds visités (visitedNode) afin de ne pas le re-traiter dans le futur de l'exécution du programme puis on récupère la liste des noeuds adjacents au nœud actuellement traité, on les ajoute dans la liste des nœuds pas encore visités (et donc à visiter prochainement) si et seulement ils n'ont pas déjà été traité (et donc dans les listes présentées ci-dessus).

Si vous voulez que je précise autre chose sur l'algorithme utilisé, n'hésitez pas.
